from .readAirTemperature import readAirTemperature
from .readAirHumidity import readAirHumidity
from .readSoilHumidity import readSoilHumdity40
from .readSoilHumidity import readSoilHumdity55
from .readSoilHumidity import readSoilHumdity70
from .readSoilHumidity import readSoilHumdity85
from .readLuminosity import readLuminosity
from .readCO2 import readCO2
from .readSmellTemperature import readTemperature
from .Adafruit_CCS811 import *
